name: deploy-tags

on:
  push:
    tags:
      - '*.*.*'

jobs:
  tests:
    strategy:
      matrix:
        os: [macos-latest,windows-latest,ubuntu-latest]
        node-version: [15.x, 14.x, 12.x]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    - run: npm test

  merge-to-versions:
    needs: tests

    runs-on: ubuntu-latest

    steps:
    - name: Merge onto version branches
      uses: alagos/regex-merge@v1.1
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
        headBranch: deploy
        branchRegex: '^emsdk-.+'

  deploy:
    needs: tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Bump version to tag
      run: npm version from-git

    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
